import {PizzaArray} from "./PizzaArray";
import {CrustArray,SizeArray} from "./AddOnArray";
import {DrinkArray,StarterArray} from "./OtherArray";


export const ComboArray=[
    {
        combo_id:0,
        combo_name:"Combo1",
        combo_desciption:"Lorem ipsum dolor sit amet, con sectetur adipiscing elit. Erat morbi viverra bibendum in sit. Ac semper arcu facilisis ornare",
        combo_price:350000,
        image:require('../image/combo1.jpg'),
        pizzas:[
            {
                pizza:PizzaArray[0],
                crust:CrustArray[2],
                size:SizeArray[1],
                quantity:1
            }
        ],
        starters:[
            {
                starter:StarterArray[0],
                quantity:1
            }
        ],
        drinks:[
            {
                drink:DrinkArray[0],
                quantity:1
            }
        ]
    },
    {
        combo_id:1,
        combo_name:"Combo1",
        combo_desciption:"Lorem ipsum dolor sit amet, con sectetur adipiscing elit. Erat morbi viverra bibendum in sit. Ac semper arcu facilisis ornare",
        combo_price:350000,
        image:require('../image/combo2.jpg'),
        pizzas:[
            {
                pizza:PizzaArray[1],
                crust:CrustArray[0],
                size:SizeArray[2],
                quantity:1
            }
        ],
        starters:[
            {
                starter:StarterArray[1],
                quantity:1
            }
        ],
        drinks:[
            {
                drink:DrinkArray[1],
                quantity:1
            }
        ]
    },
    {
        combo_id:2,
        combo_name:"Combo1",
        combo_desciption:"Lorem ipsum dolor sit amet, con sectetur adipiscing elit. Erat morbi viverra bibendum in sit. Ac semper arcu facilisis ornare",
        combo_price:350000,
        image:require('../image/combo3.jpg'),
        pizzas:[
            {
                pizza:PizzaArray[0],
                crust:CrustArray[0],
                size:SizeArray[0],
                quantity:1
            }
        ],
        starters:[
            {
                starter:StarterArray[2],
                quantity:1
            }
        ],
        drinks:[
            {
                drink:DrinkArray[2],
                quantity:1
            }
        ]
    },
    {
        combo_id:3,
        combo_name:"Combo1",
        combo_desciption:"Lorem ipsum dolor sit amet, con sectetur adipiscing elit. Erat morbi viverra bibendum in sit. Ac semper arcu facilisis ornare",
        combo_price:350000,
        image:require('../image/combo4.jpg'),
        pizzas:[
            {
                pizza:PizzaArray[1],
                crust:CrustArray[1],
                size:SizeArray[1],
                quantity:1
            }
        ],
        starters:[
            {
                starter:StarterArray[3],
                quantity:1
            }
        ],
        drinks:[
            {
                drink:DrinkArray[3],
                quantity:1
            }
        ]
    },
    {
        combo_id:4,
        combo_name:"Combo1",
        combo_desciption:"Lorem ipsum dolor sit amet, con sectetur adipiscing elit. Erat morbi viverra bibendum in sit. Ac semper arcu facilisis ornare",
        combo_price:350000,
        image:require('../image/combo5.jpg'),
        pizzas:[
            {
                pizza:PizzaArray[2],
                crust:CrustArray[2],
                size:SizeArray[2],
                quantity:1
            }
        ],
        starters:[
            {
                starter:StarterArray[4],
                quantity:1
            }
        ],
        drinks:[
            {
                drink:DrinkArray[4],
                quantity:1
            }
        ]
    },
    {
        combo_id:5,
        combo_name:"Combo1",
        combo_desciption:"Lorem ipsum dolor sit amet, con sectetur adipiscing elit. Erat morbi viverra bibendum in sit. Ac semper arcu facilisis ornare",
        combo_price:350000,
        image:require('../image/combo6.jpg'),
        pizzas:[
            {
                pizza:PizzaArray[1],
                crust:CrustArray[2],
                size:SizeArray[2],
                quantity:1
            }
        ],
        starters:[
            {
                starter:StarterArray[5],
                quantity:1
            }
        ],
        drinks:[
            {
                drink:DrinkArray[5],
                quantity:1
            }
        ]
    },
]